### ISSUE TITLE
Bcrypt version deprecated

### ISSUE THREAD

**Issue by James-Firth** [scoutforpets/objection-password#31]
I was installing objection-password through yarn today and got some errors, I think it would be best to bump the bcrypt version to `5.0.0`. 

`bcrypt@npm:3.0.8 is deprecated: versions < v5.0.0 do not handle NUL in passwords properly`

**Comment by DominicRoyStang** [comment]
Is this library still maintained?
If not, could a message be added at the top of the README to inform people who are considering installing it?

**Comment by James-Firth** [comment]
Thanks for noticing and mentioning that @DominicRoyStang!

I only looked at the date of the last commit, didn't look at the activity on the repo.

**Comment by DominicRoyStang** [comment]
For anyone watching this issue, I ended up just making my own version of this plugin (and writing my own unit tests).

See `objectionPassword.js` in this PR https://github.com/BlockedTODO/BlockedTODO/pull/269 if you're thinking of doing the same.

I would consider publishing (and maintaining) a npm package for it if there is demand for that.

**Comment by jamesdixon** [comment]
@James-Firth thanks for opening the issue!

@DominicRoyStang appreciate the suggestion. It's not a project that I'm look into everyday to check for updates as it's been fairly low maintenance, but I wouldn't call it "unmaintained."

That said, would you consider pushing your updates and additional unit tests to this project instead of creating another plugin? More than happy to accept PRs. 

I'm of the mind that if there's already a project out there that satisfies the need, commit to that instead of creating another project unless it's radically different in implementation. Give everyone the benefit of the updates instead of having to move to something else. NPM is notorious for too many packages that do the same thing; would like to not be part of that problem 👍

**Comment by DominicRoyStang** [comment]
@jamesdixon thanks for getting back to us. I'm happy to hear this library is still being maintained.

I presumed a little bit too hastily that it wasn't maintained after looking at the open issues and pull requests. I also just wanted to address a security warning in my codebase as swiftly as possible.

>I'm of the mind that if there's already a project out there that satisfies the need, commit to that instead of creating another project unless it's radically different in implementation.

I definitely agree :slightly_smiling_face: especially since this library has over 1000 weekly downloads, it makes more sense for those who depend on it to just bump up their dependencies rather than install a new one. I'd be happy to create a PR (although it will have to be later this week/weekend).

_Some questions before I do so_
If you take a look at my implementation, you'll notice a couple of differences:
- Updated bcrypt version
- Implementation is different (changed method name: `generateHash` --> `hashPassword`, use async/await syntax, changed comments)
- I use a different testing framework (jest - a wrapper around mocha) with `objection-transactional-tests`
- I test on postgresql instead of sqlite
- I use objection 2.x and knex 0.21.x

Which of those changes would you like me to include in the PR? Personally, my preference is "all of them" (execpt I would probably keep using sqlite since that looks easier to set up) but I'll let you have the final say. In particular, I'm not familiar with the testing framework `ava` so I'm not confident in my ability to translate the few tests I added/modified.

**Comment by jamesdixon** [comment]
@DominicRoyStang 

> I presumed a little bit too hastily that it wasn't maintained after looking at the open issues and pull requests. I also just wanted to address a security warning in my codebase as swiftly as possible.

All good! None of the open issues outside of bcrypt seemed mission critical, so I honestly haven't touched them. I have two full-time gigs so I'm also depending on the nature of open source here a bit 😄 

> Which of those changes would you like me to include in the PR? Personally, my preference is "all of them" (execpt I would probably keep using sqlite since that looks easier to set up) but I'll let you have the final say. In particular, I'm not familiar with the testing framework ava so I'm not confident in my ability to translate the few tests I added/modified.

I'm fine with all of those changes. However, I would keep the public API the same unless there is a really good reason to change it. And yes, I would test on SQLite as it makes contributing easier for folks.

Thanks for your help and contribution 🙌  If you'd be interested in helping to maintain, more than happy to add you!

**Comment by DominicRoyStang** [comment]
@jamesdixon Sounds good & yes I'd be happy to help maintain it 😄 
It's a bit of a busy week for me, but I'll try to find some time to put up the PR in the coming days.

**Comment by jamesdixon** [comment]
Sounds great! Thank you again

**Comment by James-Firth** [comment]
Fantastic discussion! I also use Postgres at work so having that tested is useful to me too.

Excited to get a notification when this is closed :)

**Comment by jamesdixon** [comment]
Resolved in #32
